# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-vk-secure"
BBFILE_PATTERN_meta-vk-secure = "^${LAYERDIR}/"

# Higher priority than meta-vk-custom (6) so bbappends overlay correctly
BBFILE_PRIORITY_meta-vk-secure = "8"

LAYERDEPENDS_meta-vk-secure = "core meta-vk-custom freescale-layer"
LAYERSERIES_COMPAT_meta-vk-secure = "scarthgap"
